package com.qq;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.13
 * 2017-10-10T17:22:28.525+08:00
 * Generated source version: 3.1.13
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "qqOnlineWebServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QqOnlineWebServiceHttpPost {

    /**
     * <br /><h3>获得腾讯QQ在线状态</h3><p>输入参数：QQ号码 String，默认QQ号码：8698053。返回数据：String，Y = 在线；N = 离线；E = QQ号码错误；A = 商业用户验证失败；V = 免费用户超过数量</p><br />
     */
    @WebResult(name = "string", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod
    public java.lang.String qqCheckOnline(
        @WebParam(partName = "qqCode", name = "qqCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String qqCode
    );
}
