
package com.qq;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.13
 * 2017-10-10T17:22:28.352+08:00
 * Generated source version: 3.1.13
 * 
 */
public final class QqOnlineWebServiceSoap_QqOnlineWebServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://WebXml.com.cn/", "qqOnlineWebService");

    private QqOnlineWebServiceSoap_QqOnlineWebServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QqOnlineWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QqOnlineWebService ss = new QqOnlineWebService(wsdlURL, SERVICE_NAME);
        QqOnlineWebServiceSoap port = ss.getQqOnlineWebServiceSoap12();  
        
        {
        System.out.println("Invoking qqCheckOnline...");
        java.lang.String _qqCheckOnline_qqCode = "";
        java.lang.String _qqCheckOnline__return = port.qqCheckOnline(_qqCheckOnline_qqCode);
        System.out.println("qqCheckOnline.result=" + _qqCheckOnline__return);


        }

        System.exit(0);
    }

}
