package com.huoche;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * <a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>火车时刻表 WEB 服务</strong>提供：站站查询；车次查询；车站所有车次查询。本火车时刻表 WEB 服务提供的列车时刻表数据仅供参考，如有异议以当地铁路部门颁布为准。</br>此火车时刻表Web Services请不要用于任何商业目的，若有需要请<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx" target="_blank">联系我们</a>，欢迎技术交流。 QQ：8409035<br /><strong>使用本站 WEB 服务请注明或链接本站：http://www.webxml.com.cn/ 感谢大家的支持</strong>！<br /><br />&nbsp;
 *
 * This class was generated by Apache CXF 3.1.13
 * 2017-10-10T17:38:30.610+08:00
 * Generated source version: 3.1.13
 * 
 */
@WebServiceClient(name = "TrainTimeWebService", 
                  wsdlLocation = "file:/C:/Users/Administrator/Desktop/TrainTimeWebService.asmx.xml",
                  targetNamespace = "http://WebXml.com.cn/") 
public class TrainTimeWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://WebXml.com.cn/", "TrainTimeWebService");
    public final static QName TrainTimeWebServiceSoap12 = new QName("http://WebXml.com.cn/", "TrainTimeWebServiceSoap12");
    public final static QName TrainTimeWebServiceSoap = new QName("http://WebXml.com.cn/", "TrainTimeWebServiceSoap");
    public final static QName TrainTimeWebServiceHttpPost = new QName("http://WebXml.com.cn/", "TrainTimeWebServiceHttpPost");
    public final static QName TrainTimeWebServiceHttpGet = new QName("http://WebXml.com.cn/", "TrainTimeWebServiceHttpGet");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Administrator/Desktop/TrainTimeWebService.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TrainTimeWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Administrator/Desktop/TrainTimeWebService.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public TrainTimeWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TrainTimeWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrainTimeWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TrainTimeWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TrainTimeWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TrainTimeWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TrainTimeWebServiceSoap
     */
    @WebEndpoint(name = "TrainTimeWebServiceSoap12")
    public TrainTimeWebServiceSoap getTrainTimeWebServiceSoap12() {
        return super.getPort(TrainTimeWebServiceSoap12, TrainTimeWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrainTimeWebServiceSoap
     */
    @WebEndpoint(name = "TrainTimeWebServiceSoap12")
    public TrainTimeWebServiceSoap getTrainTimeWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(TrainTimeWebServiceSoap12, TrainTimeWebServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns TrainTimeWebServiceSoap
     */
    @WebEndpoint(name = "TrainTimeWebServiceSoap")
    public TrainTimeWebServiceSoap getTrainTimeWebServiceSoap() {
        return super.getPort(TrainTimeWebServiceSoap, TrainTimeWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrainTimeWebServiceSoap
     */
    @WebEndpoint(name = "TrainTimeWebServiceSoap")
    public TrainTimeWebServiceSoap getTrainTimeWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(TrainTimeWebServiceSoap, TrainTimeWebServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns TrainTimeWebServiceHttpPost
     */
    @WebEndpoint(name = "TrainTimeWebServiceHttpPost")
    public TrainTimeWebServiceHttpPost getTrainTimeWebServiceHttpPost() {
        return super.getPort(TrainTimeWebServiceHttpPost, TrainTimeWebServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrainTimeWebServiceHttpPost
     */
    @WebEndpoint(name = "TrainTimeWebServiceHttpPost")
    public TrainTimeWebServiceHttpPost getTrainTimeWebServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(TrainTimeWebServiceHttpPost, TrainTimeWebServiceHttpPost.class, features);
    }


    /**
     *
     * @return
     *     returns TrainTimeWebServiceHttpGet
     */
    @WebEndpoint(name = "TrainTimeWebServiceHttpGet")
    public TrainTimeWebServiceHttpGet getTrainTimeWebServiceHttpGet() {
        return super.getPort(TrainTimeWebServiceHttpGet, TrainTimeWebServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrainTimeWebServiceHttpGet
     */
    @WebEndpoint(name = "TrainTimeWebServiceHttpGet")
    public TrainTimeWebServiceHttpGet getTrainTimeWebServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(TrainTimeWebServiceHttpGet, TrainTimeWebServiceHttpGet.class, features);
    }

}
