
package com.huoche;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.13
 * 2017-10-10T17:38:30.475+08:00
 * Generated source version: 3.1.13
 * 
 */
public final class TrainTimeWebServiceSoap_TrainTimeWebServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://WebXml.com.cn/", "TrainTimeWebService");

    private TrainTimeWebServiceSoap_TrainTimeWebServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TrainTimeWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TrainTimeWebService ss = new TrainTimeWebService(wsdlURL, SERVICE_NAME);
        TrainTimeWebServiceSoap port = ss.getTrainTimeWebServiceSoap();  
        
        {
        System.out.println("Invoking getStationAndTimeDataSetByTrainCode...");
        java.lang.String _getStationAndTimeDataSetByTrainCode_trainCode = "";
        java.lang.String _getStationAndTimeDataSetByTrainCode_userID = "";
        com.huoche.GetStationAndTimeDataSetByTrainCodeResponse.GetStationAndTimeDataSetByTrainCodeResult _getStationAndTimeDataSetByTrainCode__return = port.getStationAndTimeDataSetByTrainCode(_getStationAndTimeDataSetByTrainCode_trainCode, _getStationAndTimeDataSetByTrainCode_userID);
        System.out.println("getStationAndTimeDataSetByTrainCode.result=" + _getStationAndTimeDataSetByTrainCode__return);


        }
        {
        System.out.println("Invoking getStationAndTimeByStationName...");
        java.lang.String _getStationAndTimeByStationName_startStation = "";
        java.lang.String _getStationAndTimeByStationName_arriveStation = "";
        java.lang.String _getStationAndTimeByStationName_userID = "";
        com.huoche.GetStationAndTimeByStationNameResponse.GetStationAndTimeByStationNameResult _getStationAndTimeByStationName__return = port.getStationAndTimeByStationName(_getStationAndTimeByStationName_startStation, _getStationAndTimeByStationName_arriveStation, _getStationAndTimeByStationName_userID);
        System.out.println("getStationAndTimeByStationName.result=" + _getStationAndTimeByStationName__return);


        }
        {
        System.out.println("Invoking getStationAndTimeDataSetByLikeTrainCode...");
        java.lang.String _getStationAndTimeDataSetByLikeTrainCode_trainCode = "";
        java.lang.String _getStationAndTimeDataSetByLikeTrainCode_userID = "";
        com.huoche.GetStationAndTimeDataSetByLikeTrainCodeResponse.GetStationAndTimeDataSetByLikeTrainCodeResult _getStationAndTimeDataSetByLikeTrainCode__return = port.getStationAndTimeDataSetByLikeTrainCode(_getStationAndTimeDataSetByLikeTrainCode_trainCode, _getStationAndTimeDataSetByLikeTrainCode_userID);
        System.out.println("getStationAndTimeDataSetByLikeTrainCode.result=" + _getStationAndTimeDataSetByLikeTrainCode__return);


        }
        {
        System.out.println("Invoking getDetailInfoByTrainCode...");
        java.lang.String _getDetailInfoByTrainCode_trainCode = "";
        java.lang.String _getDetailInfoByTrainCode_userID = "";
        com.huoche.GetDetailInfoByTrainCodeResponse.GetDetailInfoByTrainCodeResult _getDetailInfoByTrainCode__return = port.getDetailInfoByTrainCode(_getDetailInfoByTrainCode_trainCode, _getDetailInfoByTrainCode_userID);
        System.out.println("getDetailInfoByTrainCode.result=" + _getDetailInfoByTrainCode__return);


        }
        {
        System.out.println("Invoking getVersionTime...");
        java.lang.String _getVersionTime__return = port.getVersionTime();
        System.out.println("getVersionTime.result=" + _getVersionTime__return);


        }
        {
        System.out.println("Invoking getStationName...");
        com.huoche.ArrayOfString _getStationName__return = port.getStationName();
        System.out.println("getStationName.result=" + _getStationName__return);


        }
        {
        System.out.println("Invoking getStationAndTimeByTrainCode...");
        java.lang.String _getStationAndTimeByTrainCode_trainCode = "";
        java.lang.String _getStationAndTimeByTrainCode_userID = "";
        com.huoche.ArrayOfString _getStationAndTimeByTrainCode__return = port.getStationAndTimeByTrainCode(_getStationAndTimeByTrainCode_trainCode, _getStationAndTimeByTrainCode_userID);
        System.out.println("getStationAndTimeByTrainCode.result=" + _getStationAndTimeByTrainCode__return);


        }
        {
        System.out.println("Invoking getStationNameDataSet...");
        com.huoche.GetStationNameDataSetResponse.GetStationNameDataSetResult _getStationNameDataSet__return = port.getStationNameDataSet();
        System.out.println("getStationNameDataSet.result=" + _getStationNameDataSet__return);


        }

        System.exit(0);
    }

}
